donation:
    de:
        product_id: 'donation_de_1'
        product_name: 'Spende an Wikimedia'
        subscription_plans:
            - id: '123'
              name: 'Monatliche Spende an Wikimedia'
              interval: 'Monthly'
            - id: '496'
              name: 'Vierteljährliche Spende an Wikimedia'
              interval: 'Quarterly'
            - id: '456'
              name: 'Halbjährliche Spende an Wikimedia'
              interval: 'HalfYearly'
            - id: 'ABC'
              name: 'Jährliche Spende an Wikimedia'
              interval: 'Yearly'
        return_url: 'https://test-spenden.wikimedia.de/show-donation-confirmation?id={{id}}&utoken={{updateToken}}&token={{accessToken}}'
        cancel_url: 'https://test-spenden.wikimedia.de/new?id={{id}}&utoken={{updateToken}}&token={{accessToken}}'
    en:
        product_id: 'donation_en_1'
        product_name: 'Donation to Wikimedia'
        subscription_plans:
            - id: '786'
              name: 'Monthly donation to Wikimedia'
              interval: 'Monthly'
            - id: 'GHI'
              name: 'Quarterly donation to Wikimedia'
              interval: 'Quarterly'
            - id: 'JKL'
              name: 'Half yearly donation to Wikimedia'
              interval: 'HalfYearly'
            - id: 'NMP'
              name: 'Yearly donation to Wikimedia'
              interval: 'Yearly'
        return_url: 'https://test-spenden.wikimedia.de/show-donation-confirmation?id={{id}}&utoken={{updateToken}}&token={{accessToken}}&lang=en'
        cancel_url: 'https://test-spenden.wikimedia.de/new?id={{id}}&utoken={{updateToken}}&token={{accessToken}}&lang=en'
membership:
    de:
        product_id: 'membership_de_1'
        product_name: 'Mitgliedschaftsbeitrag an Wikimedia'
        subscription_plans:
            - id: '333'
              name: 'Monatlicher Mitgliedschaftsbeitrag an Wikimedia'
              interval: 'Monthly'
            - id: 'MNT'
              name: 'Vierteljährlicher Mitgliedschaftsbeitrag an Wikimedia'
              interval: 'Quarterly'
            - id: 'DEN'
              name: 'Halbjährlicher Mitgliedschaftsbeitrag an Wikimedia'
              interval: 'HalfYearly'
            - id: 'MBB'
              name: 'Jährlicher Mitgliedschaftsbeitrag an Wikimedia'
              interval: 'Yearly'
        return_url: 'https://test-spenden.wikimedia.de/show-membership-confirmation?id={{id}}&utoken={{updateToken}}&token={{accessToken}}'
        cancel_url: 'https://test-spenden.wikimedia.de/apply-for-membership?id={{id}}&utoken={{updateToken}}&token={{accessToken}}'
    en:
        product_id: 'membership_en_1'
        product_name: 'Wikimedia Membership'
        subscription_plans:
            - id: '716'
              name: 'Monthly membership fee for Wikimedia'
              interval: 'Monthly'
            - id: 'XZA'
              name: 'Quarterly membership fee for Wikimedia'
              interval: 'Quarterly'
            - id: 'VCX'
              name: 'Half yearly membership fee for Wikimedia'
              interval: 'HalfYearly'
            - id: 'MNB'
              name: 'Yearly membership fee for Wikimedia'
              interval: 'Yearly'
        return_url: 'https://test-spenden.wikimedia.de/show-membership-confirmation?id={{id}}&utoken={{updateToken}}&token={{accessToken}}&lang=en'
        cancel_url: 'https://test-spenden.wikimedia.de/apply-for-membership?id={{id}}&utoken={{updateToken}}&token={{accessToken}}&lang=en'
